package com.infinum.queenofversions;

public enum GoogleException {

    API_NOT_AVAILABLE("API NOT AVAILABLE"),
    DOWNLOAD_NOT_PRESENT("DOWNLOAD NOT PRESENT"),
    INSTALL_NOT_ALLOWED("INSTALL NOT ALLOWED"),
    INSTALL_UNAVAILABLE("INSTALL UNAVAILABLE"),
    INTERNAL_ERROR("INTERNAL ERROR"),
    INVALID_REQUEST("INVALID REQUEST"),
    ERROR_UNKNOWN("UNKNOWN ERROR");

    GoogleException(String msg) {
    }
}
